version: 2.1

commands: 
    run-tests:
        description: Install dependencies, load db and run tests
        steps:
          - checkout
          - run: bundle install --path vendor/bundle
          - run: bundle exec rake db:create db:schema:load
          - run: rake

executors:
    docker-ruby:
        parameters:
            tag:
                type: string
        docker:
            - image: cimg/ruby:<< parameters.tag >>
            - image: cimg/postgres:15.3

workflows:
  ruby-test:
    jobs: # run test suite concurrently on different versions of Ruby
      - ruby-3-2
      - ruby-3-1
      - ruby-3-0

jobs:
  ruby-3-2:
    executor: 
        name: docker-ruby
        tag: "3.2-node"
    working_directory: ~/circleci-demo-workflows
    steps:
      - run-tests

  ruby-3-1:
    executor: 
        name: docker-ruby
        tag: "3.1-node"
    working_directory: ~/circleci-demo-workflows
    steps:
      - run-tests

  ruby-3-0:
    executor: 
        name: docker-ruby
        tag: "3.0-node"
    working_directory: ~/circleci-demo-workflows
    steps:
      - run-tests
